import 'bootstrap/dist/css/bootstrap.css';

import '../styles/global.css';
import Header from './components/header';
import Image from 'next/image';

export const metadata = {
  title: 'Cloudy',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">
        <div className="body-img">
          <Image src="/images/bg.jpg" alt="bg" fill />
        </div>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
